use proc_macro::TokenStream;
use quote::quote;
use syn::{Item, ItemMod, parse_macro_input};

pub fn error_module(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let input_mod = parse_macro_input!(item as ItemMod);

    let (_, items) = input_mod
        .content
        .expect("error_module must be used on a module with a body");

    let mut struct_names = Vec::new();
    let mut out_items = Vec::new();

    for item in items {
        if let Item::Struct(s) = &item {
            struct_names.push(s.ident.clone());
        }
        out_items.push(item);
    }

    let expanded = quote! {
        #(#out_items)*

        #[derive(Copy, Debug, Hash, PartialEq, PartialOrd, Eq, Ord)]
        #[must_use = "this `Result` may be an `Err` variant, which should be handled"]
        pub enum BResult<T, E> {
            Ok(T),
            Err(E),
        }
        pub use BResult::*;
        /// `Result` is a type that represents either success ([`Ok`]) or failure ([`Err`]).
        ///
        /// Auto generated by #[error_module]
        pub type Result<T, E> = BResult<T, E>;
        impl<T, E> Clone for BResult<T, E>
        where
            T: Clone,
            E: Clone,
        {
            #[inline]
            fn clone(&self) -> Self {
                match self {
                    Ok(x) => Ok(x.clone()),
                    Err(x) => Err(x.clone()),
                }
            }

            #[inline]
            fn clone_from(&mut self, source: &Self) {
                match (self, source) {
                    (Ok(to), Ok(from)) => to.clone_from(from),
                    (Err(to), Err(from)) => to.clone_from(from),
                    (to, from) => *to = from.clone(),
                }
            }
        }



        #[macro_export]
        macro_rules! berrors_impl_missing_errors {
            ($ty:ty, [$($v:ident),*]) => {
                berrors::berrors_internals::impl_missing_converts!(
                    $ty,
                    [#(#struct_names),*],
                    [$($v),*]
                );
            };
        }

        #(
            impl berrors::berrors_internals::ErrCode for #struct_names {
                const CODE: &'static str = stringify!(#struct_names);
            }
        )*

        pub enum GlobalErrors<E: berrors::berrors_internals::ComparableError> {
            #(
                #struct_names(#struct_names),
            )*
            _PHANTOM(std::marker::PhantomData<E>)
        }

        // impl<E: berrors::berrors_internals::ComparableError<GlobalErrorsIndices>> GlobalErrors<E> {
        //     pub const fn code_to_str(code: GlobalErrorsIndices) -> &'static str {
        //         match code {
        //             #(
        //                 GlobalErrorsIndices::#struct_names => stringify!(#struct_names),
        //             )*
        //         }
        //     }
        // }
    };

    TokenStream::from(expanded)
}
