use cfg_if::cfg_if;
use proc_macro::TokenStream;
use quote::quote;
use syn::{Item, ItemMod, parse_macro_input};

pub fn skerry_mod(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let input_mod = parse_macro_input!(item as ItemMod);

    let (_, items) = input_mod
        .content
        .expect("error_module must be used on a module with a body");

    let mut struct_names = Vec::new();
    let mut out_items = Vec::new();

    for item in items {
        if let Item::Struct(s) = &item {
            struct_names.push(s.ident.clone());
        }
        out_items.push(item);
    }

    let mut feature_expand = quote! {};

    #[cfg(feature = "custom_result")]
    {
        feature_expand.extend(quote!{
            /// Auto generated by Skerry
            pub enum Result<T, E> {
                /// Contains the success value
                Ok(T),
                /// Contains the error value
                Err(E)
            }
            pub use Result::*;

            impl<T, E, I> std::ops::Try for Result<T, E>
            where
                E: IntoSkerryGlobal<Error = I> + From<GlobalErrors<I>>,
                I: skerry::skerry_internals::SkerryError,
            {
                type Output = T;
                type Residual = std::result::Result<std::convert::Infallible, E>;

                #[inline]
                fn from_output(output: Self::Output) -> Self {
                    Ok(output)
                }

                #[inline]
                fn branch(self) -> std::ops::ControlFlow<Self::Residual, Self::Output> {
                    match self {
                        Ok(v) => std::ops::ControlFlow::Continue(v),
                        Err(e) => std::ops::ControlFlow::Break(std::result::Result::Err(e.into())),
                    }
                }
            }

            pub trait IntoSkerryGlobal {
                type Error: skerry::skerry_internals::SkerryError;

                fn into_global_error(self) -> GlobalErrors<Self::Error>;
            }

            impl<T, E, I, F> std::ops::FromResidual<std::result::Result<std::convert::Infallible, E>> for Result<T, F>
            where
                E: IntoSkerryGlobal<Error = I>,
                I: skerry::skerry_internals::SkerryError,
                F: From<GlobalErrors<I>>,
            {
                #[inline]
                #[track_caller]
                fn from_residual(residual: std::result::Result<std::convert::Infallible, E>) -> Self {
                    match residual {
                        std::result::Result::Err(e) => Err(F::from(e.into_global_error())),
                    }
                }
            }

            #(
                impl IntoSkerryGlobal for #struct_names {
                    type Error = #struct_names;

                    fn into_global_error(self) -> GlobalErrors<Self::Error> {
                        GlobalErrors::#struct_names(self)
                    }
                }
            )*
        });
    }

    let expanded = quote! {
        #(#out_items)*

        #feature_expand

        pub enum GlobalErrors<E: skerry::skerry_internals::SkerryError> {
            #(
                #struct_names(#struct_names),
            )*
            _PHANTOM(std::marker::PhantomData<E>)
        }

        #[macro_export]
        macro_rules! skerry_impl_missing_errors {
            ($ty:ty, [$($v:ident),*], no_expand) => {
                skerry::skerry_internals::impl_missing_converts!(
                    $ty,
                    [#(#struct_names),*],
                    [$($v),*],
                    no_expand
                );
            };
            ($ty:ty, [$($v:ident),*]) => {
                skerry::skerry_internals::impl_missing_converts!(
                    $ty,
                    [#(#struct_names),*],
                    [$($v),*]
                );
            };
        }

        #(
            impl skerry::skerry_internals::SkerryError for #struct_names {}

            skerry_impl_missing_errors!(#struct_names, [#struct_names], no_expand);

            impl<I: Into<#struct_names>> From<I> for GlobalErrors<#struct_names> {
                fn from(val: I) -> Self {
                    Self::#struct_names(val.into())
                }
            }
        )*

    };

    TokenStream::from(expanded)
}
